name: MSBuild Reusable Workflow

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      configuration:
        required: true
        type: string
      maxCpu:
        required: false
        default: 4
        type: number

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Locate Solution File
        id: find_sln
        run: |
          $solution = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse -Filter "*.sln" | Select-Object -ExpandProperty FullName
          if ($solution) { 
            echo "SOLUTION_PATH=$solution" >> $env:GITHUB_ENV
            echo "✅ Solution file found: $solution"
          } else { 
            echo "❌ No solution file found!"
            exit 1
          }
        shell: pwsh

      - name: Restore NuGet Packages
        run: nuget restore "$env:SOLUTION_PATH"
        shell: cmd

      - name: Setup MSBuild Path
        run: |
          echo "Setting up MSBuild environment..."
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        shell: pwsh

      - name: Build Solution with MSBuild
        run: |
 
